export const GET_INPUT_VALUE = 'GET_INPUT_VALUE';
export const GET_SENT_MESSAGE_INFO = 'GET_SENT_MESSAGE_INFO';
export const STORE_ATTACHED_FILE = 'STORE_ATTACHED_FILE';
export const REMOVE_ATTACHED_FILE = 'REMOVE_ATTACHED_FILE';
export const RESET_FORM_STATE = 'RESET_FORM_STATE';
export const GET_SENT_MESSAGE_ID = 'GET_SENT_MESSAGE_ID';
export const GET_SENT_MESSAGE_STATUS = 'GET_SENT_MESSAGE_STATUS';
